name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92d5f04830d621107774a1e2422dcbbee7d99b335fd1ebbcda5e112341bc5917"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
