name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6338293e7957e5f19ef9eb2ec402cfc1f54ae44b2855000fb9ec152262563fa1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
