name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61096140e875236ab09b5c7d734eb78c7ef404135d311f2958cf99becbdbe3af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
